package com.example.Entity;

public interface TableNames {
  String TABLE_NAME_EMPLOYEE = "newHope";
}
//    Column     |          Type          | Collation | Nullable |             Default
//        ---------------+------------------------+-----------+----------+----------------------------------
//        id            | integer                |           | not null | generated by default as identity
//    designation   | character varying(255) |           |          |
//    manager_id_my | integer                |           |          |
//    name          | character varying(255) |           |          |
//    manager_id    | integer                |           |          |
//    Indexes:
//    "pricing_employee_pkey" PRIMARY KEY, btree (id)
//    Foreign-key constraints:
//    "fks6vlat9oolpprukc344nc0rgy" FOREIGN KEY (manager_id) REFERENCES pricing_employee(id)
//    Referenced by:
//    TABLE "pricing_employee" CONSTRAINT "fks6vlat9oolpprukc344nc0rgy" FOREIGN KEY (manager_id) REFERENCES pricing_employee(id)
//
//    Column     |          Type          | Collation | Nullable |             Default
//    ---------------+------------------------+-----------+----------+----------------------------------
//    id            | integer                |           | not null | generated by default as identity
//    designation   | character varying(255) |           |          |
//    manager_id_my | integer                |           |          |
//    name          | character varying(255) |           |          |
//    manager_id    | integer                |           |          |
//    Indexes:
//    "test_employee_pkey" PRIMARY KEY, btree (id)
//    Foreign-key constraints:
//    "fkgdlbra8vnsc154vt35y8l2ivp" FOREIGN KEY (manager_id) REFERENCES test_employee(id)
//    Referenced by:
//    TABLE "test_employee" CONSTRAINT "fkgdlbra8vnsc154vt35y8l2ivp" FOREIGN KEY (manager_id) REFERENCES test_employee(id)